[package]
name = "advent-of-code-2018"
version = "0.0.0"
authors = ["Glenn Pratt <glennpratt@gmail.com>"]

[lib]
bench = false

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
regex = "1"
rust-crypto = "*"
